#!/usr/bin/env bash
# Send a file to a server using scp

SRC_PATH="$1"
TARGET_IP="$2"
USR="$3"
KEY_PATH="$4"

if [ "$#" -ge 3 ]; then
   scp -o StrictHostKeyChecking=no -i "$KEY_PATH" "$SRC_PATH" "$USR"@"$TARGET_IP":~/
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi