#!/usr/bin/env bash
#install and partitaily configure nginx on a web server


#installation
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

#write a simple html test file
echo "server {
    listen 80;
    server_name localhost;

    location / {
        echo 'Hello World!';
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null


#apply configurations
sudo service nginx start
