#!/usr/bin/env bash
#install and partitaily configure nginx on a web server


#installation
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

#write a simple html test file
echo "Hello World!" > /var/www/html/index.html

#test nginx
sudo nginx -t

#apply configurations
sudo service nginx start
