#!/usr/bin/env bash
#Install and configure HAproxy on ubuntu machine

#Gain super user previlagies
sudo su

#update and install
sudo apt-get update
sudo apt-get -y install haproxy

#Save a copy of the current configuartion state
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

#configure haproxy to manage two servers
front_end="#configure frontend\nfrontend web_frontend\n\tbind \*:80\n\tmode http\n\tdefault_backend web_backend\n\n"
back_end="#configure backend\nbackend web_backend\n\tbalance roundrobin\n\tserver 316877-web-01 107.23.160.42:80 check\n\tserver 316877-web-02 52.91.131.122:80 check\n"

echo "$front_end $back_end" | sudo tee -a /etc/haproxy/haproxy.cfg

#verify configuration syntax
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

#start haproxy
sudo systemctl start haproxy

#varify if configuration is managable by init scripts
#varify if init script is present
sudo ls /etc/init.d/haproxy

#Enable automatic startup
sudo systemctl enable haproxy
