#!/usr/bin/env bash
# The use of branched statements

start=0

while [ "$start" -lt 10 ]; do

      if [ "$start" -eq 3 ]; then
          echo "bad luck"
      elif [ "$start" -eq 7 ]; then
          echo "good luck"
      else
          echo "Best School"
      fi

      ((start += 1))
done
