#!/usr/bin/env bash
# branched statements: case pattern match statement

start=1

while [ "$start" -lt 21 ]; do

      case "$start" in
      5)
      echo "bad luck from China"
      ;;
      10)
      echo "bad luck from Japan"
      ;;
      18)
      echo "Good luck from Italy"
      ;;
      esac

      echo "$start"

      ((start += 1))
done
