#!/usr/bin/env bash
# branched statements: case pattern match statement

start=1

while [ "$start" -ne 21 ]; do

      case "$start" in
      4)
      echo "bad luck from China"
      ;;
      9)
      echo "bad luck from Japan"
      ;;
      17)
      echo "Good luck from Italy"
      ;;
      *)
      echo "$start"
      ;;
      esac

      ((start += 1))
done
