#!/usr/bin/env bash
# Implementing a 12 hour clock

hour=0

while [ "$hour" -lt 13 ]; do

    echo "Hour: $hour"

    min=1
    while [ "$min" -lt 60 ]; do
        echo "$min"
	((min += 1))
    done

    ((hour += 1))
done
